[bumpver]
current_version = "0.0.0"
version_pattern = "MAJOR.MINOR.PATCH"
commit = true
tag = true
push = false
commit_message = "bump version {old_version} -> {new_version}"
tag_message = "{new_version}"
tag_scope = "global"

[bumpver.file_patterns]

"src/__init__.py" = [
    '__version__ = "{version}"'
]

"src/config/config.py" = [
    'VERSION = "{version}"'
]